name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Exécute l'action à chaque push sur la branche principale
  workflow_dispatch:  # Permet d'exécuter l'action manuellement

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Se connecter à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construire et tagger l’image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/node-js-simple:latest
            ${{ secrets.DOCKER_USERNAME }}/node-js-simple:${{ github.sha }}
